config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  resources :categories, only: %i[index show new create destroy] do
    resources :expenses, only: [:new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :expense
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon_url, presence: true
  # associations
  belongs_to :author, class_name: 'User'
  has_many :categorizations, dependent: :destroy
  has_many :expenses, through: :categorizations
  def total_amount
    expenses.sum(:amount)
  end
end

app/models/detail.rb
class Detail < ApplicationRecord
validates :name, presence: true
  validates :amount, presence: true
  # associations
  belongs_to :author, class_name: 'User'
  has_many :categorizations, dependent: :destroy
  has_many :categories
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true
  # associations
  belongs_to :author, class_name: 'User'
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, allow_blank: false
  validates :email, presence: true, allow_blank: false
  validates :password, presence: true, allow_blank: false
  has_many :expenses, dependent: :destroy, foreign_key: :author_id
  has_many :categories, dependent: :destroy, foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @group_details = Expense.joins(:categorizations, :categories)
      .where('expenses.id = categorizations.expense_id')
      .where('categories.id = categorizations.category_id')
      .where('categories.id = ?', params[:id]).order('expenses.created_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @author = current_user
    @category = Category.new(category_params)
    @category.author = @author

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon_url, :user_id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @category = current_user.categories # Category.find(params[:category])
  end

  def create
    print params
    expense = Expense.new(name: params[:name], amount: params[:amount], author_id: params[:author_id])

    if expense.save
      print params
      categorization = Categorization.new(category_id: params[:category], expense_id: expense.id)
      categorization.save
      redirect_to category_path(params[:category]), notice: 'expense was successfully created.'

    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @transactions = @user.transactions
    @categories = @user.categories
  end

  def new
    @user = User.new
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class ="c-index-cont">
    <div>
        <%= render "shared/navbar" %>
        <%= render "shared/messages" %>
        
            <% @categories.each do |category| %>
                <div class="c-index-cont__category__name">
                <%= link_to category_path(category), class: "c-index-cont__category" do %>
                        <div class="c-detail">
                        <div class="img-name">
                        <%= image_tag(category.icon_url, class: "c-index-cont__category__name__icon") %>
                        <p class="c-index-cont__category__name__text"><%= category.name %></p>
                        </div>
                        <p class="c-index-cont__item__text"><%= category.created_at.strftime("%d %b %y") %></p>
                        </div>
                        <div class="amt">                    
                            <p class="c-index-cont__category__amount"><%= number_to_currency(category.total_amount)%></p>
                        </div>
                <% end %>
            
        </div>
        <% end %>
    </div>

    <%= link_to new_category_path, class: "c-index-cont__new-category" do %>
        <p class="c-index-cont__new-category__text">ADD CATEGORY</p>
    <% end %>
</div>

app/views/categories/new.html.erb
<div  class="c-new-cont">
    <%= form_with model: @category, url: categories_path do |form|%>

       <div class="c-new-cont__title">
            <%= link_to :back do %>
                <i class="fa fa-arrow-left"></i>
                <% end %>
                <h2 class="c-new-cont__title__text">ADD CATEGORY</h2>
                <div class="c-new-cont__title__btn">
                    <%= form.submit "Next", class: "c-new-cont__title__btn__text" %>
                </div>
       </div>
       <%= render "shared/messages" %>
         <div class="c-new-cont__form">
                <%= form.text_field :name, placeholder: "Name", class: "c-new-cont__form__label" %>
                <%= form.text_field :icon_url, placeholder: "Icon url", class: "c-new-cont__form__label" %>
         </div>
        <% end %>
        <% if flash[:error] %>
                <div><%= flash[:error] %></div>
        <% end %>
    </div>
</div>

app/views/categories/show.html.erb
<div class="c-show-cont">
    <div>
        <%= render "shared/navbar" %>
        <%= render "shared/messages" %>
        <div class="c-show-cont__title">
            <p class="c-show-cont__title__text"><%= @category.name %></p>
            <p class="c-show-cont__title__text"><%= number_to_currency (@category.total_amount) %></p>
        </div>

        <% @group_details.each do |expense| %>
            <div class="c-show-cont__items">
                <div class="c-show-cont__item">
                    <p class="c-show-cont__item__text"><%= expense.name %></p>
                    <p class="c-show-cont__item__text"><%= expense.created_at.strftime("%d %b %y") %></p>
                </div>
                <p class="c-show-cont__item__text"><%= number_to_currency(expense.amount) %></p>
            </div>
        <% end %>
    </div>
    <%= link_to new_category_expense_path(@category), class: "c-show-cont__btn" do %>
        <p class="c-show-cont__text">Add Transaction</p>
    <% end %>
</div>

app/views/expenses/new.html.erb
<div class="t-cont">
    <%= form_with url: category_expenses_path, locale: true, method: :post do |form|%>
        <div class='t-cont__form'>
            <%= link_to :back do %>
            <i class="fas fa-arrow-left"></i>
            <% end %>
            <h2 class="t-cont__form__title">New Transaction</h2>
            <div class="t-cont__form__input">
                <%= form.submit "Save", class: "t-cont__form__input__btn" %>
            </div>
        </div>
        <%= render "shared/messages" %>
        <div class="t-cont__form__input">
            <%= form.text_field :name, class: "t-cont__form__input__field", required: true, placeholder: "Name" %>
            <%= form.number_field :amount, required: true, class: "t-cont__form__input__field", placeholder: "Amount" %>
        </div>
        <div class="t-cont__form__input__label">
        <p class="t-cont__form__input__label__detail">Select Category</p>
        <%= form.select :category, current_user.categories.map { |c| [c.name, c.id] }, required: true, class: "t-cont__form__input__field" %>
        </div>
        <%= form.hidden_field :author_id, value: current_user.id %>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="home-cont">
    <div class="home-cont__header">
        <h1 class="home-cont__header__title">BUDGET APP</h1>
    </div>

    <div class="home-cont__body">
        <%= link_to "Log In", new_user_session_path, class: "login" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "signup" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_messages.html.erb
<% if notice.present?%>
    <p class="notice"><%= notice %></p>
    <%end%>
    <% if alert.present?%>
    <p class="alert"><%= alert %></p>
    <%end%>

app/views/shared/_navbar.html.erb
<div class="navbar">
<% if params[:id].present? %>
    <%= link_to categories_path, class: "navbar-item" do %>
        <i class="fa fa-arrow-left"></i>
        <% end %>
        <% else %>
        <%= link_to :back , class: "navbar-item" do %>
            <i class="fa fa-arrow-left"></i>
            <% end %>
            <% end %>
            <% p params  %>
            <% if params[:action] == 'show' %>
            <h2 class="navbar-title">Transactions</h2>
            <% else %>
            <h2 class="navbar-title"><%= params[:controller] %></h2>
            <% end %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
</div>